name: ci
on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/ci.yaml'
      - 'hosts/nixos-common.nix'
      - 'flake.nix'
      - 'flake.lock'
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  ci:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Check Nixpkgs input
        uses: DeterminateSystems/flake-checker-action@v8
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v13
      - name: Check flake
        run: |
          nix flake check \
            --all-systems \
            --no-build
